# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
release_channel = release
maven_group = de.mrjulsen.ctt
archives_name = createthreadedtrains
main_class_name = CreateThreadedTrains
enabled_platforms = fabric,forge
java_version = 17
datapack_version = 10

# Mod Info
display_name = Create: Threaded Trains
authors = MrJulsen
description = Offloads the railway network ticks to a separate thread that runs in parallel to the server tick, greatly improving performance in large railway networks.
homepage = https://www.curseforge.com/minecraft/mc-mods/create-threaded_trains
issues = https://github.com/MisterJulsen/Create-Threaded-Trains/issues
source = https://github.com/MisterJulsen/Create-Threaded-Trains
license = GNU General Public License v3.0
icon = icon.png
discord = https://discord.gg/AeSbNgvc7f

# Minecraft properties
minecraft_version = 1.19.2
parchment_version = 2022.11.27
next_unsupported_minecraft_version=1.20

# Dependencies
fabric_loader_version = 0.15.11
fabric_api_version = 0.77.0+1.19.2
forge_version = 1.19.2-43.3.13
forge_loader_version = 40
forge_dependency_version = 40.2.4

modmenu_version = 4.1.2
forge_config_api_port_version = 4.2.11
create_fabric_version = 0.5.1-f-build.1416+mc1.19.2
create_forge_version = 0.5.1.f-46
create_forge_version_dependency = 0.5.1.f
registrate_forge_version = MC1.19-1.1.5
flywheel_forge_version = 0.6.10-20
